
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "#Spring2016"
  host: localhost
  database: AddressApp
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "#Spring2016"
  host: localhost
  database: AddressApp
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "#Spring2016"
  host: localhost
  database: AddressApp
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#
production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "#Spring2016"
  host: localhost
  database: AddressApp
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
